//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc_Otelim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bildirim
    {
        public int ID { get; set; }
        public int KullanıcıID { get; set; }
        public string text { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
    
        public virtual Kullanıcı Kullanıcı { get; set; }
    }
}
