//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc_Otelim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kullanıcı
    {
        public Kullanıcı()
        {
            this.Bildirim = new HashSet<Bildirim>();
            this.FavoriOtel = new HashSet<FavoriOtel>();
            this.FavoriOtel1 = new HashSet<FavoriOtel>();
            this.OtelPuanlandırma = new HashSet<OtelPuanlandırma>();
            this.Rezervasyon = new HashSet<Rezervasyon>();
            this.SonGörüntülenen = new HashSet<SonGörüntülenen>();
            this.OdaYorum = new HashSet<OdaYorum>();
            this.OtelPuanlandırma1 = new HashSet<OtelPuanlandırma>();
            this.OtelYorum = new HashSet<OtelYorum>();
            this.Rezervasyon1 = new HashSet<Rezervasyon>();
            this.SonGörüntülenen1 = new HashSet<SonGörüntülenen>();
        }
    
        public int ID { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public string Mail { get; set; }
        public string Sifre { get; set; }
        public Nullable<System.DateTime> DoğumTarihi { get; set; }
    
        public virtual ICollection<Bildirim> Bildirim { get; set; }
        public virtual ICollection<FavoriOtel> FavoriOtel { get; set; }
        public virtual ICollection<FavoriOtel> FavoriOtel1 { get; set; }
        public virtual ICollection<OtelPuanlandırma> OtelPuanlandırma { get; set; }
        public virtual ICollection<Rezervasyon> Rezervasyon { get; set; }
        public virtual ICollection<SonGörüntülenen> SonGörüntülenen { get; set; }
        public virtual ICollection<OdaYorum> OdaYorum { get; set; }
        public virtual ICollection<OtelPuanlandırma> OtelPuanlandırma1 { get; set; }
        public virtual ICollection<OtelYorum> OtelYorum { get; set; }
        public virtual ICollection<Rezervasyon> Rezervasyon1 { get; set; }
        public virtual ICollection<SonGörüntülenen> SonGörüntülenen1 { get; set; }
    }
}
