//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc_Otelim.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OtelModel1 : DbContext
    {
        public OtelModel1()
            : base("name=OtelModel1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Admin> Admin { get; set; }
        public DbSet<Bildirim> Bildirim { get; set; }
        public DbSet<FavoriOtel> FavoriOtel { get; set; }
        public DbSet<Kullanıcı> Kullanıcı { get; set; }
        public DbSet<Oda> Oda { get; set; }
        public DbSet<OdaFoto> OdaFoto { get; set; }
        public DbSet<OdaYorum> OdaYorum { get; set; }
        public DbSet<Otel> Otel { get; set; }
        public DbSet<OtelFoto> OtelFoto { get; set; }
        public DbSet<OtelPuanlandırma> OtelPuanlandırma { get; set; }
        public DbSet<OtelYorum> OtelYorum { get; set; }
        public DbSet<OtelYöneticisi> OtelYöneticisi { get; set; }
        public DbSet<Rezervasyon> Rezervasyon { get; set; }
        public DbSet<SonGörüntülenen> SonGörüntülenen { get; set; }
    }
}
