//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc_Otelim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Oda
    {
        public Oda()
        {
            this.OdaFoto = new HashSet<OdaFoto>();
            this.OdaYorum = new HashSet<OdaYorum>();
            this.Rezervasyon = new HashSet<Rezervasyon>();
            this.OdaFoto1 = new HashSet<OdaFoto>();
            this.OdaYorum1 = new HashSet<OdaYorum>();
            this.Rezervasyon1 = new HashSet<Rezervasyon>();
        }
    
        public int ID { get; set; }
        public string OdaTürü { get; set; }
        public Nullable<int> Kapasite { get; set; }
        public int OtelID { get; set; }
        public string name { get; set; }
    
        public virtual Otel Otel { get; set; }
        public virtual ICollection<OdaFoto> OdaFoto { get; set; }
        public virtual ICollection<OdaYorum> OdaYorum { get; set; }
        public virtual ICollection<Rezervasyon> Rezervasyon { get; set; }
        public virtual ICollection<OdaFoto> OdaFoto1 { get; set; }
        public virtual ICollection<OdaYorum> OdaYorum1 { get; set; }
        public virtual Otel Otel1 { get; set; }
        public virtual ICollection<Rezervasyon> Rezervasyon1 { get; set; }
    }
}
