//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc_Otelim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OdaFoto
    {
        public int ID { get; set; }
        public Nullable<int> OdaID { get; set; }
        public string Link { get; set; }
    
        public virtual Oda Oda { get; set; }
        public virtual Oda Oda1 { get; set; }
    }
}
