//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc_Otelim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Otel
    {
        public Otel()
        {
            this.FavoriOtel = new HashSet<FavoriOtel>();
            this.FavoriOtel1 = new HashSet<FavoriOtel>();
            this.Oda = new HashSet<Oda>();
            this.Oda1 = new HashSet<Oda>();
            this.OtelFoto = new HashSet<OtelFoto>();
            this.OtelPuanlandırma = new HashSet<OtelPuanlandırma>();
            this.OtelYorum = new HashSet<OtelYorum>();
            this.OtelYöneticisi = new HashSet<OtelYöneticisi>();
            this.SonGörüntülenen = new HashSet<SonGörüntülenen>();
            this.OtelFoto1 = new HashSet<OtelFoto>();
            this.OtelPuanlandırma1 = new HashSet<OtelPuanlandırma>();
            this.OtelYorum1 = new HashSet<OtelYorum>();
            this.OtelYöneticisi1 = new HashSet<OtelYöneticisi>();
            this.SonGörüntülenen1 = new HashSet<SonGörüntülenen>();
        }
    
        public int ID { get; set; }
        public string OtelAdı { get; set; }
        public Nullable<int> OtelTürüID { get; set; }
        public Nullable<int> OdaSayısı { get; set; }
        public Nullable<int> YıldızSayısı { get; set; }
        public Nullable<float> Puan { get; set; }
        public Nullable<int> YöneticiID { get; set; }
        public string Şehir { get; set; }
    
        public virtual ICollection<FavoriOtel> FavoriOtel { get; set; }
        public virtual ICollection<FavoriOtel> FavoriOtel1 { get; set; }
        public virtual ICollection<Oda> Oda { get; set; }
        public virtual ICollection<Oda> Oda1 { get; set; }
        public virtual ICollection<OtelFoto> OtelFoto { get; set; }
        public virtual ICollection<OtelPuanlandırma> OtelPuanlandırma { get; set; }
        public virtual ICollection<OtelYorum> OtelYorum { get; set; }
        public virtual ICollection<OtelYöneticisi> OtelYöneticisi { get; set; }
        public virtual ICollection<SonGörüntülenen> SonGörüntülenen { get; set; }
        public virtual ICollection<OtelFoto> OtelFoto1 { get; set; }
        public virtual ICollection<OtelPuanlandırma> OtelPuanlandırma1 { get; set; }
        public virtual ICollection<OtelYorum> OtelYorum1 { get; set; }
        public virtual ICollection<OtelYöneticisi> OtelYöneticisi1 { get; set; }
        public virtual ICollection<SonGörüntülenen> SonGörüntülenen1 { get; set; }
    }
}
